In [1]:
# Import the required libraries:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
data_2020 = pd.read_csv("C:/Users/mural/Desktop/data_for_good/2020_brightside_data.csv")
data_2020.head(3)

RespondentID    newid  collectorid             location             date  \
0  110005085857  5085857    270167554          LONDONDERRY  8/11/2020 19:02   
1  110005135726  5135726    270167553  LIONS VIEW BLDG III  8/19/2020 13:37   
2  110005213106  5213106    270167559       MOUNT PLEASANT  8/30/2020 20:26   

   nbr_relation  sense_commun  safe_violence  safe_covid  food_enough  ...  \
0           2.0           2.0            2.0         2.0          1.0  ...   
1           2.0           2.0            2.0         3.0          1.0  ...   
2           NaN           2.0            NaN         0.0          NaN  ...   

   bside_dur  bside_pre                                    bside_pre_other  \
0        2.0        2.0                                                NaN   
1        3.0        0.0  Lived with my partner until the relationship e...   
2        4.0        3.0                                                NaN   

   bside_pre_muni  bside_pre_muni_other  \
0             0.0               Burnaby   
1             0.0          Pitt Meadows   
2             1.0                   NaN   

                                       surv_feedback  surv_who surv_who_other  \
0                                                NaN       1.0            NaN   
1  I really would like that the building gets a b...       1.0            NaN   
2                                                NaN       1.0            NaN   

   surv_hear surv_hear_other  
0        2.0             NaN  
1        3.0             NaN  
2        2.0             NaN  

[3 rows x 237 columns]

In [3]:
data_2020.describe()

RespondentID         newid   collectorid  nbr_relation  sense_commun  \
count  2.230000e+02  2.230000e+02  2.230000e+02    211.000000    202.000000   
mean   1.100053e+11  5.319374e+06  2.701676e+08      2.052133      2.009901   
std    1.144239e+05  1.144239e+05  6.902472e+00      0.509091      0.661598   
min    1.100051e+11  5.085857e+06  2.701675e+08      0.000000      0.000000   
25%    1.100053e+11  5.264874e+06  2.701676e+08      2.000000      2.000000   
50%    1.100053e+11  5.287459e+06  2.701676e+08      2.000000      2.000000   
75%    1.100053e+11  5.342154e+06  2.701676e+08      2.000000      2.000000   
max    1.100059e+11  5.929096e+06  2.701676e+08      3.000000      3.000000   

       safe_violence  safe_covid  food_enough  food_access  food_variety  ...  \
count     198.000000  206.000000   212.000000   207.000000    208.000000  ...   
mean        1.924242    2.135922     1.363208     1.545894      1.740385  ...   
std         0.482504    0.759313     0.868165     0.953568      1.133548  ...   
min         0.000000    0.000000     0.000000     0.000000      0.000000  ...   
25%         2.000000    2.000000     1.000000     1.000000      1.000000  ...   
50%         2.000000    2.000000     1.000000     1.000000      1.000000  ...   
75%         2.000000    3.000000     1.000000     2.000000      2.000000  ...   
max         3.000000    3.000000     5.000000     5.000000      5.000000  ...   

       walk_aid_na  walk_aid_other  educ_level  educ_level_other  imm_status  \
count          4.0             6.0  214.000000               0.0  214.000000   
mean           1.0             1.0    3.467290               NaN    0.612150   
std            0.0             0.0    1.819652               NaN    0.576571   
min            1.0             1.0    1.000000               NaN    0.000000   
25%            1.0             1.0    2.000000               NaN    0.000000   
50%            1.0             1.0    3.000000               NaN    1.000000   
75%            1.0             1.0    5.000000               NaN    1.000000   
max            1.0             1.0    7.000000               NaN    2.000000   

        bside_dur   bside_pre  bside_pre_muni    surv_who  surv_hear  
count  216.000000  216.000000      220.000000  219.000000  218.00000  
mean     3.541667    2.504630        0.831818    0.958904    1.87156  
std      0.770457    1.564126        0.431506    0.220821    0.53626  
min      2.000000    0.000000        0.000000    0.000000    0.00000  
25%      3.000000    2.000000        1.000000    1.000000    2.00000  
50%      4.000000    2.000000        1.000000    1.000000    2.00000  
75%      4.000000    2.000000        1.000000    1.000000    2.00000  
max      5.000000    8.000000        2.000000    2.000000    5.00000  

[8 rows x 203 columns]

In [4]:
data_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223 entries, 0 to 222
Columns: 237 entries, RespondentID to surv_hear_other
dtypes: float64(200), int64(3), object(34)
memory usage: 413.0+ KB


In [5]:
# Get the numeric data:

data_2020_numeric = data_2020._get_numeric_data()
data_2020_numeric.head()

RespondentID    newid  collectorid  nbr_relation  sense_commun  \
0  110005085857  5085857    270167554           2.0           2.0   
1  110005135726  5135726    270167553           2.0           2.0   
2  110005213106  5213106    270167559           NaN           2.0   
3  110005213123  5213123    270167561           2.0           3.0   
4  110005213195  5213195    270167561           3.0           3.0   

   safe_violence  safe_covid  food_enough  food_access  food_variety  ...  \
0            2.0         2.0          1.0          1.0           1.0  ...   
1            2.0         3.0          1.0          1.0           1.0  ...   
2            NaN         0.0          NaN          NaN           NaN  ...   
3            3.0         3.0          2.0          1.0           3.0  ...   
4            2.0         3.0          1.0          2.0           2.0  ...   

   walk_aid_na  walk_aid_other  educ_level  educ_level_other  imm_status  \
0          NaN             NaN         5.0               NaN         1.0   
1          NaN             NaN         3.0               NaN         0.0   
2          NaN             NaN         1.0               NaN         1.0   
3          NaN             NaN         6.0               NaN         0.0   
4          NaN             NaN         2.0               NaN         0.0   

   bside_dur  bside_pre  bside_pre_muni  surv_who  surv_hear  
0        2.0        2.0             0.0       1.0        2.0  
1        3.0        0.0             0.0       1.0        3.0  
2        4.0        3.0             1.0       1.0        2.0  
3        2.0        7.0             0.0       1.0        2.0  
4        3.0        2.0             0.0       1.0        1.0  

[5 rows x 203 columns]

In [6]:
# Create the required X and Y variable:

X = data_2020_numeric.drop(['RespondentID','newid','collectorid','hlth_happy'], axis =1 )

y = data_2020_numeric['hlth_happy']

X = np.nan_to_num(X)

y = np.nan_to_num(y)

In [7]:
print(len(X))
print(len(y))

223
223


In [9]:
# Split the dataframe into test and train:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [10]:
# Implement the Random Forest Classfier:

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

clf = RandomForestClassifier(random_state=0)

In [11]:
# Fit the required Random Forest:

clf.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [12]:
# Predict the values with trained model:

y_pred = clf.predict(X_test)

In [13]:
# Evaluate the model:

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 0  2  0  0  0]
 [ 0 18  3  0  0]
 [ 0 13  4  0  0]
 [ 0  0  4  0  0]
 [ 0  1  0  0  0]]
              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00         2
         2.0       0.53      0.86      0.65        21
         3.0       0.36      0.24      0.29        17
         4.0       0.00      0.00      0.00         4
         6.0       0.00      0.00      0.00         1

    accuracy                           0.49        45
   macro avg       0.18      0.22      0.19        45
weighted avg       0.38      0.49      0.41        45

0.4888888888888889


C:\Users\mural\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [22]:
# Look for the features that are important:

from sklearn.feature_selection import SelectFromModel
sfm = SelectFromModel(clf, threshold=0.1)

# Train the selector
sfm.fit(X_train, y_train)

# Print the name of these important features:
for feature_list_index in sfm.get_support(indices=True):
    print(data_2020_numeric[feature_list_index])

In [19]:
print(sfm.get_support(indices = True))

[]


In [20]:
# Find the importance factors of the features:
clf.feature_importances_

array([7.37924357e-03, 6.73838973e-03, 5.11531580e-03, 7.16857980e-03,
       9.06800608e-03, 1.41271404e-02, 1.62639255e-02, 1.24994941e-02,
       1.13601053e-02, 9.76687317e-03, 7.96234965e-03, 4.93224008e-03,
       5.78144771e-03, 5.34224229e-03, 6.76142228e-03, 8.43109222e-03,
       6.71723124e-03, 8.45391362e-03, 2.62100369e-02, 1.40324640e-02,
       9.91636060e-03, 3.59096367e-03, 1.26562102e-02, 5.35177694e-03,
       1.16434565e-02, 3.40536238e-03, 1.00644697e-02, 3.28488785e-03,
       7.00728556e-03, 3.51556084e-03, 9.50401558e-03, 2.21684969e-03,
       1.44438044e-02, 5.21861054e-03, 8.34252242e-03, 1.30709669e-02,
       7.41642934e-03, 1.30796397e-02, 1.13798276e-02, 8.30351312e-03,
       6.87208868e-03, 7.74777626e-03, 3.32525200e-03, 5.01630126e-03,
       4.21283429e-03, 3.98909758e-03, 3.23637137e-03, 3.80464617e-03,
       5.15147844e-03, 5.41956007e-03, 1.61466729e-02, 3.83407229e-02,
       3.11662346e-03, 2.11423544e-03, 1.73385843e-03, 1.51950382e-03,
      

In [23]:
# Find the features which are the most important:
cor = data_2020_numeric.corr()
#sns.heatmap(cor, annot=True)
cor.head()

RespondentID     newid  collectorid  nbr_relation  sense_commun  \
RespondentID      1.000000  1.000000     0.013706     -0.135709     -0.128994   
newid             1.000000  1.000000     0.013706     -0.135709     -0.128994   
collectorid       0.013706  0.013706     1.000000      0.050536     -0.060184   
nbr_relation     -0.135709 -0.135709     0.050536      1.000000      0.287517   
sense_commun     -0.128994 -0.128994    -0.060184      0.287517      1.000000   

              safe_violence  safe_covid  food_enough  food_access  \
RespondentID      -0.077058   -0.043667     0.003231     0.081767   
newid             -0.077058   -0.043667     0.003231     0.081767   
collectorid       -0.087108   -0.087864     0.112850     0.032657   
nbr_relation       0.208905    0.151936     0.021337    -0.022864   
sense_commun       0.337551    0.249496    -0.055007    -0.088972   

              food_variety  ...  walk_aid_na  walk_aid_other  educ_level  \
RespondentID      0.132377  ...          NaN             NaN    0.060583   
newid             0.132377  ...          NaN             NaN    0.060583   
collectorid       0.129082  ...          NaN             NaN    0.041276   
nbr_relation     -0.039509  ...          NaN             NaN   -0.008626   
sense_commun     -0.035383  ...          NaN             NaN   -0.012991   

              educ_level_other  imm_status  bside_dur  bside_pre  \
RespondentID               NaN    0.101108   0.019644   0.129179   
newid                      NaN    0.101108   0.019644   0.129179   
collectorid                NaN    0.000022  -0.028031   0.164254   
nbr_relation               NaN   -0.047262   0.037868  -0.010382   
sense_commun               NaN    0.000000   0.009893   0.042963   

              bside_pre_muni  surv_who  surv_hear  
RespondentID        0.111265  0.146100  -0.052013  
newid               0.111265  0.146100  -0.052013  
collectorid        -0.024220 -0.078527  -0.012980  
nbr_relation       -0.179324 -0.020592  -0.026946  
sense_commun       -0.011914 -0.029529   0.158576  

[5 rows x 203 columns]

In [24]:
#Correlation with output variable
cor_target = abs(cor["hlth_happy"])

#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.25]
relevant_features

food_afford            0.252482
food_worry             0.275890
covid_info_satis       0.327580
house_stable           0.389842
apprch_bside           0.378158
comm_news_satisf       0.261379
food_health_last_12    0.322553
food_few_last_12       0.280972
food_skip_last_12      0.297326
food_hunger_last_12    0.258917
hlth_phys              0.396343
hlth_mental            0.513792
hlth_happy             1.000000
event_easy             0.260168
event_connect          0.336934
rlns_close             0.269730
rlns_lonely            0.271605
rlns_welcome           0.387511
rlns_safe              0.329213
Name: hlth_happy, dtype: float64

### This is a pretty big insight for determining what are the variables that affect the final happiness ratings of the residents

In [50]:
relevant_list = list(relevant_features.index)

relevant_list

#relevant_list.append('hlth_happy')

#type(relevant_list)

relevant_list

['food_afford',
 'food_worry',
 'covid_info_satis',
 'house_stable',
 'apprch_bside',
 'comm_news_satisf',
 'food_health_last_12',
 'food_few_last_12',
 'food_skip_last_12',
 'food_hunger_last_12',
 'hlth_phys',
 'hlth_mental',
 'hlth_happy',
 'event_easy',
 'event_connect',
 'rlns_close',
 'rlns_lonely',
 'rlns_welcome',
 'rlns_safe']

In [51]:
data_feat= data_2020_numeric[relevant_list]

In [52]:
data_feat

food_afford  food_worry  covid_info_satis  house_stable  apprch_bside  \
0            1.0         1.0               2.0           3.0           2.0   
1            1.0         1.0               1.0           1.0           1.0   
2            NaN         NaN               3.0           NaN           3.0   
3            4.0         2.0               1.0           1.0           1.0   
4            1.0         1.0               2.0           3.0           2.0   
..           ...         ...               ...           ...           ...   
218          1.0         1.0               NaN           2.0           NaN   
219          3.0         5.0               2.0           5.0           4.0   
220          1.0         1.0               1.0           2.0           1.0   
221          2.0         1.0               4.0           4.0           4.0   
222          3.0         3.0               5.0           3.0           5.0   

     comm_news_satisf  food_health_last_12  food_few_last_12  \
0                 3.0                  2.0               2.0   
1                 1.0                  2.0               2.0   
2                 2.0                  NaN               NaN   
3                 2.0                  1.0               1.0   
4                 2.0                  2.0               2.0   
..                ...                  ...               ...   
218               NaN                  1.0               2.0   
219               2.0                  1.0               1.0   
220               2.0                  2.0               2.0   
221               4.0                  1.0               1.0   
222               5.0                  1.0               1.0   

     food_skip_last_12  food_hunger_last_12  hlth_phys  hlth_mental  \
0                  2.0                  2.0        4.0          4.0   
1                  2.0                  2.0        1.0          1.0   
2                  NaN                  NaN        2.0          1.0   
3                  2.0                  2.0        4.0          5.0   
4                  2.0                  2.0        3.0          3.0   
..                 ...                  ...        ...          ...   
218                2.0                  2.0        2.0          2.0   
219                2.0                  1.0        4.0          3.0   
220                2.0                  2.0        3.0          4.0   
221                2.0                  2.0        3.0          5.0   
222                1.0                  1.0        5.0          2.0   

     hlth_happy  event_easy  event_connect  rlns_close  rlns_lonely  \
0           3.0         NaN            NaN         4.0          4.0   
1           2.0         NaN            NaN         3.0          2.0   
2           NaN         NaN            NaN         4.0          NaN   
3           2.0         NaN            NaN         1.0          5.0   
4           2.0         NaN            NaN         2.0          4.0   
..          ...         ...            ...         ...          ...   
218         5.0         NaN            NaN         4.0          2.0   
219         3.0         2.0            3.0         4.0          2.0   
220         3.0         3.0            3.0         3.0          3.0   
221         4.0         1.0            4.0         4.0          4.0   
222         3.0         1.0            1.0         3.0          4.0   

     rlns_welcome  rlns_safe  
0             3.0        4.0  
1             5.0        5.0  
2             4.0        4.0  
3             1.0        2.0  
4             3.0        4.0  
..            ...        ...  
218           0.0        0.0  
219           3.0        1.0  
220           2.0        4.0  
221           4.0        2.0  
222           4.0        2.0  

[223 rows x 19 columns]

### Again apply the RF here:

In [55]:
# Create the required X variable:
X = data_feat.drop(['hlth_happy'], axis =1 )

y = data_feat['hlth_happy']

X = np.nan_to_num(X)

y = np.nan_to_num(y)

In [56]:
print(y)

[3. 2. 0. 2. 2. 2. 2. 2. 3. 1. 3. 3. 4. 2. 3. 1. 4. 4. 2. 2. 3. 6. 3. 3.
 2. 2. 1. 3. 2. 3. 3. 3. 2. 3. 4. 4. 3. 3. 3. 3. 3. 4. 3. 3. 2. 2. 3. 2.
 1. 5. 3. 1. 2. 3. 2. 2. 3. 1. 2. 3. 3. 4. 1. 2. 2. 2. 2. 2. 1. 2. 3. 2.
 3. 4. 3. 3. 1. 2. 3. 2. 1. 2. 2. 2. 2. 2. 2. 3. 6. 3. 2. 2. 4. 1. 4. 3.
 2. 2. 2. 4. 2. 2. 4. 2. 3. 2. 3. 3. 4. 1. 3. 2. 2. 2. 5. 6. 2. 4. 4. 3.
 2. 4. 2. 2. 4. 2. 4. 2. 2. 2. 2. 3. 5. 3. 2. 3. 4. 2. 2. 3. 3. 2. 2. 2.
 3. 2. 6. 2. 3. 2. 2. 3. 2. 3. 2. 3. 3. 4. 2. 2. 3. 2. 2. 3. 3. 1. 2. 3.
 3. 3. 0. 2. 1. 3. 2. 2. 6. 2. 2. 3. 5. 2. 3. 2. 6. 2. 2. 3. 3. 3. 2. 3.
 2. 3. 2. 2. 3. 2. 3. 6. 3. 2. 2. 2. 2. 2. 3. 2. 2. 2. 2. 3. 3. 3. 3. 2.
 2. 4. 5. 3. 3. 4. 3.]


In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

clf = RandomForestClassifier(random_state=0)

clf.fit(X_train, y_train)

print(y_test)
y_pred = clf.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[2. 2. 3. 4. 3. 2. 2. 2. 2. 3. 3. 3. 2. 2. 2. 6. 3. 2. 3. 2. 3. 3. 2. 3.
 3. 4. 2. 3. 4. 3. 2. 3. 3. 2. 2. 1. 4. 2. 1. 2. 2. 2. 2. 3. 3.]
[[ 1  1  0  0  0]
 [ 1 16  4  0  0]
 [ 0 11  5  1  0]
 [ 0  0  3  1  0]
 [ 0  1  0  0  0]]
              precision    recall  f1-score   support

         1.0       0.50      0.50      0.50         2
         2.0       0.55      0.76      0.64        21
         3.0       0.42      0.29      0.34        17
         4.0       0.50      0.25      0.33         4
         6.0       0.00      0.00      0.00         1

    accuracy                           0.51        45
   macro avg       0.39      0.36      0.36        45
weighted avg       0.48      0.51      0.48        45

0.5111111111111111


C:\Users\mural\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# The accuracy score increased a little.

In [ ]:
# Write the analysis for the same 